"use client"
import './globals.css'
import type { Metadata } from 'next'
import { ColorProvider } from '../contexts/ColorContext.';
import { ClickProvider } from '../contexts/ClickContext';
import { Inter } from 'next/font/google'
import { AnimatePresence } from "framer-motion"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AnimatePresence>
      <ColorProvider>
      <ClickProvider>
      <body className={inter.className}>{children}</body>
      </ClickProvider>
    </ColorProvider>
    </AnimatePresence>
    </html>
  )
}
